#!/usr/bin/env node
/**
 * Post-build steps that only make sense for a static host.
 *
 *  1. `404.html` — GitHub Pages has no server-side rewrites, so a deep link like
 *     /learn/ruby/blocks 404s on a hard navigation. Pages serves 404.html for any
 *     unmatched path, so a copy of index.html there boots the SPA and the router takes
 *     over. This is the standard approach and the reason it is not a redirect hack is
 *     that the URL is preserved exactly.
 *
 *  2. `sitemap.xml` and `robots.txt` — generated from the real route list so crawlers
 *     can find every lesson. Pre-rendering actual HTML per lesson is the next step and
 *     is tracked in ROADMAP.md.
 *
 *  3. `sw.js` — a service worker with a precache manifest, for offline reading.
 *
 *  4. A size report, so a regression in the initial payload is visible in CI output.
 */
import { readFile, writeFile, copyFile, readdir, stat } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { gzipSync } from 'node:zlib'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const DIST = path.join(ROOT, 'dist')
const SITE = process.env.SITE_URL ?? 'https://suniljaiswaar.github.io'
const BASE = (process.env.BASE_PATH ?? '/').replace(/\/?$/, '/')

/** Budget for the initial payload, gzipped. Exceeding it fails the build. */
const INITIAL_BUDGET_KB = 180

if (!existsSync(DIST)) {
  console.error('✖ dist/ does not exist — run the build first')
  process.exit(1)
}

const catalog = JSON.parse(
  await readFile(path.join(ROOT, 'src', 'generated', 'catalog.json'), 'utf8'),
)

/* ---------------------------------------------------------- SPA fallback */

await copyFile(path.join(DIST, 'index.html'), path.join(DIST, '404.html'))

// Stops GitHub Pages running the output through Jekyll, which would drop files
// and directories beginning with an underscore.
await writeFile(path.join(DIST, '.nojekyll'), '')

/* -------------------------------------------------------------- sitemap */

const staticRoutes = [
  '', 'learn', 'roadmaps', 'practice', 'interview', 'review',
  'progress', 'playground', 'graph', 'search', 'contribute',
]

const urls = [
  ...staticRoutes.map((route) => ({
    loc: `${SITE}${BASE}${route}`,
    priority: route === '' ? '1.0' : '0.7',
    changefreq: 'weekly',
  })),
  ...catalog.tracks.map((track) => ({
    loc: `${SITE}${BASE}learn/${track.slug}`,
    priority: '0.8',
    changefreq: 'weekly',
  })),
  ...catalog.tracks.flatMap((track) =>
    track.modules.flatMap((module) =>
      module.lessons.map((lesson) => ({
        loc: `${SITE}${BASE}learn/${track.slug}/${lesson.slug}`,
        priority: '0.9',
        changefreq: 'monthly',
      })),
    ),
  ),
  ...catalog.tracks.length
    ? JSON.parse(await readFile(path.join(ROOT, 'src', 'generated', 'roadmaps.json'), 'utf8'))
        .roadmaps.map((r) => ({
          loc: `${SITE}${BASE}roadmaps/${r.id}`,
          priority: '0.7',
          changefreq: 'monthly',
        }))
    : [],
]

const today = new Date().toISOString().slice(0, 10)
await writeFile(
  path.join(DIST, 'sitemap.xml'),
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
  `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
  urls
    .map(
      (u) =>
        `  <url><loc>${u.loc.replace(/\/$/, '') || u.loc}</loc>` +
        `<lastmod>${today}</lastmod>` +
        `<changefreq>${u.changefreq}</changefreq>` +
        `<priority>${u.priority}</priority></url>`,
    )
    .join('\n') +
  `\n</urlset>\n`,
)

await writeFile(
  path.join(DIST, 'robots.txt'),
  `User-agent: *\nAllow: /\n\nSitemap: ${SITE}${BASE}sitemap.xml\n`,
)

/* ------------------------------------------------------- service worker */

/**
 * Precache the shell and the generated content, so a lesson already read is readable
 * offline. Hashed assets are cached on first use rather than precached, because
 * precaching Monaco would mean a ~4 MB download nobody asked for.
 */
const assets = await readdir(path.join(DIST, 'assets'))

// The shell is exactly what index.html loads eagerly — read it from the HTML rather
// than pattern-matching filenames, which would also catch lazily loaded chunks whose
// names happen to start with "index-".
const indexHtml = await readFile(path.join(DIST, 'index.html'), 'utf8')
const shell = [
  ...indexHtml.matchAll(/(?:src|href)="[^"]*assets\/([^"]+\.(?:js|css))"/g),
].map((m) => m[1])

const version = `${today}-${shell.join('|').length}`
const precache = [
  `${BASE}`,
  `${BASE}index.html`,
  `${BASE}manifest.webmanifest`,
  ...shell.map((file) => `${BASE}assets/${file}`),
]

await writeFile(
  path.join(DIST, 'sw.js'),
  `/* Generated by scripts/postbuild.mjs — do not edit. */
const VERSION = ${JSON.stringify(version)};
const SHELL = 'rubiq-shell-' + VERSION;
const RUNTIME = 'rubiq-runtime-' + VERSION;
const PRECACHE = ${JSON.stringify(precache, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(SHELL)
      // addAll rejects the whole install if any single request fails, which would mean
      // one missing file leaves the user with no service worker at all.
      .then((cache) => Promise.allSettled(PRECACHE.map((url) => cache.add(url))))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        keys.filter((k) => k !== SHELL && k !== RUNTIME).map((k) => caches.delete(k)),
      ))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Navigations: network first so a deploy is picked up, falling back to the cached
  // shell when offline. The SPA router resolves the path client-side either way.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request).catch(() =>
        caches.match(${JSON.stringify(`${BASE}index.html`)}).then(
          (cached) => cached ?? new Response('Offline', { status: 503 }),
        ),
      ),
    );
    return;
  }

  // Hashed assets are immutable, so cache-first is safe and makes repeat loads instant.
  event.respondWith(
    caches.match(request).then((cached) => {
      if (cached) return cached;
      return fetch(request).then((response) => {
        if (response.ok && response.type === 'basic') {
          const copy = response.clone();
          void caches.open(RUNTIME).then((cache) => cache.put(request, copy));
        }
        return response;
      });
    }),
  );
});
`,
)

/* ----------------------------------------------------------- size report */

const initial = [...indexHtml.matchAll(/(?:src|href)="([^"]*assets\/[^"]+\.(?:js|css))"/g)]
  .map((m) => m[1].replace(BASE, '').replace(/^\//, ''))

let initialBytes = 0
const rows = []
for (const asset of initial) {
  const file = path.join(DIST, asset)
  if (!existsSync(file)) continue
  const gz = gzipSync(await readFile(file)).length
  initialBytes += gz
  rows.push([asset.replace('assets/', ''), gz])
}

const kb = (bytes) => `${(bytes / 1024).toFixed(1)} KB`

console.log('\nInitial payload (gzipped):')
for (const [name, bytes] of rows.sort((a, b) => b[1] - a[1])) {
  console.log(`  ${kb(bytes).padStart(9)}  ${name}`)
}
console.log(`  ${'─'.repeat(9)}`)
console.log(`  ${kb(initialBytes).padStart(9)}  total  (budget ${INITIAL_BUDGET_KB} KB)`)

// Lazy chunks, for visibility. Monaco living here rather than above is the point.
const lazy = []
for (const file of assets) {
  if (initial.some((i) => i.endsWith(file))) continue
  const full = path.join(DIST, 'assets', file)
  if (!(await stat(full)).isFile()) continue
  lazy.push([file, gzipSync(await readFile(full)).length])
}
console.log('\nLargest lazy chunks (gzipped):')
for (const [name, bytes] of lazy.sort((a, b) => b[1] - a[1]).slice(0, 5)) {
  console.log(`  ${kb(bytes).padStart(9)}  ${name}`)
}

console.log(
  `\nWrote 404.html, .nojekyll, sitemap.xml (${urls.length} urls), robots.txt, sw.js\n`,
)

if (initialBytes / 1024 > INITIAL_BUDGET_KB) {
  console.error(
    `✖ initial payload is ${kb(initialBytes)}, over the ${INITIAL_BUDGET_KB} KB budget.\n` +
    `  Something that should be lazy is being loaded eagerly — check for a static import\n` +
    `  of a route, of Monaco, or of the search index.\n`,
  )
  process.exit(1)
}
